#!/data/data/com.termux/files/usr/bin/bash env

########################################
#  BYPASS Setup Script
#  Author: ToniKun <https://t.me/topjohnw>
#  Dependencies: bash and wget.
#
########################################

# Update and upgrade
pkg up -y && pkg upgrade -y

# Switch permissive
su -c 'setenforce 0'

# Install dependencies
time apt install rsync aapt neofetch toilet ncurses-utils tsu openssl-tool ruby wget -y

# Fetch the ELF and setup
[[ "$(uname -m)" =~ 'aarch64' ]] && {
    tsu -c 'wget https://github.com/Tonikun/MakingUnknown/raw/51f27f620ce9bae7407316860434e72c108a49da/tonikun_cli'
    tsu -c 'chmod a+x tonikun_cli'
    tsu -c ./tonikun_cli
} || printf "Your architecture isn't officially supported yet."
